#
# Copyright 2015 SmartBear Software
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
#
package WWW::SwaggerClient::UserachievementsApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::SwaggerClient::ApiClient;
use WWW::SwaggerClient::Configuration;

sub new {
    my $class   = shift;
    my $default_api_client = $WWW::SwaggerClient::Configuration::api_client ? $WWW::SwaggerClient::Configuration::api_client  : WWW::SwaggerClient::ApiClient->new;
    my (%self) = (
        'api_client' => $default_api_client,
        @_
    );

    #my $self = {
    #    #api_client => $options->{api_client}
    #    api_client => $default_api_client
    #}; 

    bless \%self, $class;

}

#
# g_et_version_user_achievements
#
# Returns a list of achievements earned by users based on query parameters.\n              Query parameters can be combined as desired.\n              Award type id is required if achievement id is provided
# 
# @param string $x_partner_token Your secret partner token (required)
# @param string $x_user_token The token you recieved when you authenticated the user (required)
# @param int $award_type_id  (optional)
# @param int $user_id  (optional)
# @param int $patrol_id  (optional)
# @param int $achievement_id  (optional)
# @return string
#
sub g_et_version_user_achievements {
    my ($self, %args) = @_;

    
    # verify the required parameter 'x_partner_token' is set
    unless (exists $args{'x_partner_token'}) {
      croak("Missing the required parameter 'x_partner_token' when calling g_et_version_user_achievements");
    }
    
    # verify the required parameter 'x_user_token' is set
    unless (exists $args{'x_user_token'}) {
      croak("Missing the required parameter 'x_user_token' when calling g_et_version_user_achievements");
    }
    

    # parse inputs
    my $_resource_path = '/v1/user_achievements';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/xml', 'application/json', 'application/octet-stream', 'text/plain');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'award_type_id'}) {
        $query_params->{'award_type_id'} = $self->{api_client}->to_query_value($args{'award_type_id'});
    }# query params
    if ( exists $args{'user_id'}) {
        $query_params->{'user_id'} = $self->{api_client}->to_query_value($args{'user_id'});
    }# query params
    if ( exists $args{'patrol_id'}) {
        $query_params->{'patrol_id'} = $self->{api_client}->to_query_value($args{'patrol_id'});
    }# query params
    if ( exists $args{'achievement_id'}) {
        $query_params->{'achievement_id'} = $self->{api_client}->to_query_value($args{'achievement_id'});
    }
    # header params
    if ( exists $args{'x_partner_token'}) {
        $header_params->{'X-Partner-Token'} = $self->{api_client}->to_header_value($args{'x_partner_token'});
    }# header params
    if ( exists $args{'x_user_token'}) {
        $header_params->{'X-User-Token'} = $self->{api_client}->to_header_value($args{'x_user_token'});
    }
    
    
    my $_body_data;
    

    # authentication setting, if any
    my $auth_settings = [];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
    
}
#
# g_et_version_user_achievements_parameters
#
# Returns a list of possible values to be used in querying
# 
# @param string $x_partner_token Your secret partner token (required)
# @param string $x_user_token The token you recieved when you authenticated the user (required)
# @return string
#
sub g_et_version_user_achievements_parameters {
    my ($self, %args) = @_;

    
    # verify the required parameter 'x_partner_token' is set
    unless (exists $args{'x_partner_token'}) {
      croak("Missing the required parameter 'x_partner_token' when calling g_et_version_user_achievements_parameters");
    }
    
    # verify the required parameter 'x_user_token' is set
    unless (exists $args{'x_user_token'}) {
      croak("Missing the required parameter 'x_user_token' when calling g_et_version_user_achievements_parameters");
    }
    

    # parse inputs
    my $_resource_path = '/v1/user_achievements/parameters';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/xml', 'application/json', 'application/octet-stream', 'text/plain');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    
    # header params
    if ( exists $args{'x_partner_token'}) {
        $header_params->{'X-Partner-Token'} = $self->{api_client}->to_header_value($args{'x_partner_token'});
    }# header params
    if ( exists $args{'x_user_token'}) {
        $header_params->{'X-User-Token'} = $self->{api_client}->to_header_value($args{'x_user_token'});
    }
    
    
    my $_body_data;
    

    # authentication setting, if any
    my $auth_settings = [];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
    
}
#
# g_et_version_user_achievements_id
#
# Returns achievment details, including requirements, for a given achievement
# 
# @param string $x_partner_token Your secret partner token (required)
# @param string $x_user_token The token you recieved when you authenticated the user (required)
# @param int $id Id of the achievement being updated (required)
# @param int $award_type_id Id of the Award Type for the achievement being updated (required)
# @return string
#
sub g_et_version_user_achievements_id {
    my ($self, %args) = @_;

    
    # verify the required parameter 'x_partner_token' is set
    unless (exists $args{'x_partner_token'}) {
      croak("Missing the required parameter 'x_partner_token' when calling g_et_version_user_achievements_id");
    }
    
    # verify the required parameter 'x_user_token' is set
    unless (exists $args{'x_user_token'}) {
      croak("Missing the required parameter 'x_user_token' when calling g_et_version_user_achievements_id");
    }
    
    # verify the required parameter 'id' is set
    unless (exists $args{'id'}) {
      croak("Missing the required parameter 'id' when calling g_et_version_user_achievements_id");
    }
    
    # verify the required parameter 'award_type_id' is set
    unless (exists $args{'award_type_id'}) {
      croak("Missing the required parameter 'award_type_id' when calling g_et_version_user_achievements_id");
    }
    

    # parse inputs
    my $_resource_path = '/v1/user_achievements/{id}';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/xml', 'application/json', 'application/octet-stream', 'text/plain');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'award_type_id'}) {
        $query_params->{'award_type_id'} = $self->{api_client}->to_query_value($args{'award_type_id'});
    }
    # header params
    if ( exists $args{'x_partner_token'}) {
        $header_params->{'X-Partner-Token'} = $self->{api_client}->to_header_value($args{'x_partner_token'});
    }# header params
    if ( exists $args{'x_user_token'}) {
        $header_params->{'X-User-Token'} = $self->{api_client}->to_header_value($args{'x_user_token'});
    }
    # path params
    if ( exists $args{'id'}) {
        my $_base_variable = "{" . "id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }
    
    my $_body_data;
    

    # authentication setting, if any
    my $auth_settings = [];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
    
}
#
# p_ost_version_user_achievements_id
#
# Update achievment details, including requirements, for a given achievement
# 
# @param string $x_partner_token Your secret partner token (required)
# @param string $x_user_token The token you recieved when you authenticated the user (required)
# @param int $id Id of the user achievement being updated (required)
# @param int $award_type_id Id of the Award Type for the achievement being updated (required)
# @param string $achievement[completed_on] Date the achievement was completed in YYYY-MM-DD format (optional)
# @param string $achievement[award_card_front_image_content] Base 64 encoded image content of the front of an award card for the achievement. Currently ignored unless the achievement is a BSA Merit Badge. (optional)
# @param string $achievement[award_card_images_type] File extension of the award card images - must be the same type for the front and back, if included. Currently ignored unless the achievement is a BSA Merit Badge. (optional)
# @param string $achievement[award_card_back_image_content] Base 64 encoded image content of the back of an award card for the achievement. Currently ignored unless the achievement is a BSA Merit Badge. (optional)
# @param int $achievement[children][id] Id of the requirement to be updated (optional)
# @param string $achievement[children][completed_on] Date the requirement was completed in YYYY-MM-DD format (optional)
# @return string
#
sub p_ost_version_user_achievements_id {
    my ($self, %args) = @_;

    
    # verify the required parameter 'x_partner_token' is set
    unless (exists $args{'x_partner_token'}) {
      croak("Missing the required parameter 'x_partner_token' when calling p_ost_version_user_achievements_id");
    }
    
    # verify the required parameter 'x_user_token' is set
    unless (exists $args{'x_user_token'}) {
      croak("Missing the required parameter 'x_user_token' when calling p_ost_version_user_achievements_id");
    }
    
    # verify the required parameter 'id' is set
    unless (exists $args{'id'}) {
      croak("Missing the required parameter 'id' when calling p_ost_version_user_achievements_id");
    }
    
    # verify the required parameter 'award_type_id' is set
    unless (exists $args{'award_type_id'}) {
      croak("Missing the required parameter 'award_type_id' when calling p_ost_version_user_achievements_id");
    }
    

    # parse inputs
    my $_resource_path = '/v1/user_achievements/{id}';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/xml', 'application/json', 'application/octet-stream', 'text/plain');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    
    # header params
    if ( exists $args{'x_partner_token'}) {
        $header_params->{'X-Partner-Token'} = $self->{api_client}->to_header_value($args{'x_partner_token'});
    }# header params
    if ( exists $args{'x_user_token'}) {
        $header_params->{'X-User-Token'} = $self->{api_client}->to_header_value($args{'x_user_token'});
    }
    # path params
    if ( exists $args{'id'}) {
        my $_base_variable = "{" . "id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }
    # form params
    if ( exists $args{'award_type_id'} ) {
        
        $form_params->{'award_type_id'} = $self->{api_client}->to_form_value($args{'award_type_id'});
        
    }# form params
    if ( exists $args{'achievement[completed_on]'} ) {
        
        $form_params->{'achievement[completed_on]'} = $self->{api_client}->to_form_value($args{'achievement[completed_on]'});
        
    }# form params
    if ( exists $args{'achievement[award_card_front_image_content]'} ) {
        
        $form_params->{'achievement[award_card_front_image_content]'} = $self->{api_client}->to_form_value($args{'achievement[award_card_front_image_content]'});
        
    }# form params
    if ( exists $args{'achievement[award_card_images_type]'} ) {
        
        $form_params->{'achievement[award_card_images_type]'} = $self->{api_client}->to_form_value($args{'achievement[award_card_images_type]'});
        
    }# form params
    if ( exists $args{'achievement[award_card_back_image_content]'} ) {
        
        $form_params->{'achievement[award_card_back_image_content]'} = $self->{api_client}->to_form_value($args{'achievement[award_card_back_image_content]'});
        
    }# form params
    if ( exists $args{'achievement[children][id]'} ) {
        
        $form_params->{'achievement[children][id]'} = $self->{api_client}->to_form_value($args{'achievement[children][id]'});
        
    }# form params
    if ( exists $args{'achievement[children][completed_on]'} ) {
        
        $form_params->{'achievement[children][completed_on]'} = $self->{api_client}->to_form_value($args{'achievement[children][completed_on]'});
        
    }
    my $_body_data;
    

    # authentication setting, if any
    my $auth_settings = [];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
    
}


1;
