#
# Copyright 2015 SmartBear Software
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
#
package WWW::SwaggerClient::YouthsApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::SwaggerClient::ApiClient;
use WWW::SwaggerClient::Configuration;

sub new {
    my $class   = shift;
    my $default_api_client = $WWW::SwaggerClient::Configuration::api_client ? $WWW::SwaggerClient::Configuration::api_client  : WWW::SwaggerClient::ApiClient->new;
    my (%self) = (
        'api_client' => $default_api_client,
        @_
    );

    #my $self = {
    #    #api_client => $options->{api_client}
    #    api_client => $default_api_client
    #}; 

    bless \%self, $class;

}

#
# p_ost_version_youths
#
# Create a youth
# 
# @param string $x_partner_token Your secret partner token (required)
# @param string $x_user_token The token you recieved when you authenticated the user (required)
# @param string $youth[last_name]  (optional)
# @param string $youth[first_name]  (optional)
# @param string $youth[email]  (optional)
# @param string $youth[born_on]  (optional)
# @param string $youth[scout]  (optional)
# @param string $youth[home_phone]  (optional)
# @param string $youth[cell_phone]  (optional)
# @param int $youth[patrol_id]  (optional)
# @param int $youth[household_id]  (optional)
# @param string $youth[profile_photo]  (optional)
# @param int $youth[leadership_position_id]  (optional)
# @param boolean $youth[create_money_account]  (optional)
# @param boolean $youth[send_invite]  (optional)
# @return string
#
sub p_ost_version_youths {
    my ($self, %args) = @_;

    
    # verify the required parameter 'x_partner_token' is set
    unless (exists $args{'x_partner_token'}) {
      croak("Missing the required parameter 'x_partner_token' when calling p_ost_version_youths");
    }
    
    # verify the required parameter 'x_user_token' is set
    unless (exists $args{'x_user_token'}) {
      croak("Missing the required parameter 'x_user_token' when calling p_ost_version_youths");
    }
    

    # parse inputs
    my $_resource_path = '/v1/youths';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/xml', 'application/json', 'application/octet-stream', 'text/plain');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    
    # header params
    if ( exists $args{'x_partner_token'}) {
        $header_params->{'X-Partner-Token'} = $self->{api_client}->to_header_value($args{'x_partner_token'});
    }# header params
    if ( exists $args{'x_user_token'}) {
        $header_params->{'X-User-Token'} = $self->{api_client}->to_header_value($args{'x_user_token'});
    }
    
    # form params
    if ( exists $args{'youth[last_name]'} ) {
        
        $form_params->{'youth[last_name]'} = $self->{api_client}->to_form_value($args{'youth[last_name]'});
        
    }# form params
    if ( exists $args{'youth[first_name]'} ) {
        
        $form_params->{'youth[first_name]'} = $self->{api_client}->to_form_value($args{'youth[first_name]'});
        
    }# form params
    if ( exists $args{'youth[email]'} ) {
        
        $form_params->{'youth[email]'} = $self->{api_client}->to_form_value($args{'youth[email]'});
        
    }# form params
    if ( exists $args{'youth[born_on]'} ) {
        
        $form_params->{'youth[born_on]'} = $self->{api_client}->to_form_value($args{'youth[born_on]'});
        
    }# form params
    if ( exists $args{'youth[scout]'} ) {
        
        $form_params->{'youth[scout]'} = $self->{api_client}->to_form_value($args{'youth[scout]'});
        
    }# form params
    if ( exists $args{'youth[home_phone]'} ) {
        
        $form_params->{'youth[home_phone]'} = $self->{api_client}->to_form_value($args{'youth[home_phone]'});
        
    }# form params
    if ( exists $args{'youth[cell_phone]'} ) {
        
        $form_params->{'youth[cell_phone]'} = $self->{api_client}->to_form_value($args{'youth[cell_phone]'});
        
    }# form params
    if ( exists $args{'youth[patrol_id]'} ) {
        
        $form_params->{'youth[patrol_id]'} = $self->{api_client}->to_form_value($args{'youth[patrol_id]'});
        
    }# form params
    if ( exists $args{'youth[household_id]'} ) {
        
        $form_params->{'youth[household_id]'} = $self->{api_client}->to_form_value($args{'youth[household_id]'});
        
    }# form params
    if ( exists $args{'youth[profile_photo]'} ) {
        
        $form_params->{'youth[profile_photo]'} = $self->{api_client}->to_form_value($args{'youth[profile_photo]'});
        
    }# form params
    if ( exists $args{'youth[leadership_position_id]'} ) {
        
        $form_params->{'youth[leadership_position_id]'} = $self->{api_client}->to_form_value($args{'youth[leadership_position_id]'});
        
    }# form params
    if ( exists $args{'youth[create_money_account]'} ) {
        
        $form_params->{'youth[create_money_account]'} = $self->{api_client}->to_form_value($args{'youth[create_money_account]'});
        
    }# form params
    if ( exists $args{'youth[send_invite]'} ) {
        
        $form_params->{'youth[send_invite]'} = $self->{api_client}->to_form_value($args{'youth[send_invite]'});
        
    }
    my $_body_data;
    

    # authentication setting, if any
    my $auth_settings = [];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
    
}


1;
