package WWW::SwaggerClient::Object::EventDetailsEntity;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'rsvp_deadline' => 'string',
    'event_id' => 'int',
    'is_registration_closed?' => 'string',
    'hiking_miles' => 'string',
    'payment_required_to_rsvp' => 'string',
    'activity_at' => 'string',
    'end_at' => 'string',
    'event_type' => 'string',
    'vcal' => 'string',
    'description' => 'string',
    'adult_fee' => 'string',
    'camping_nights' => 'string',
    'dues' => 'string',
    'guests_allowed' => 'string',
    'canoeing_miles' => 'string',
    'title' => 'string',
    'service_hours' => 'string'
};

my $attribute_map = {
    'rsvp_deadline' => 'rsvp_deadline',
    'event_id' => 'event_id',
    'is_registration_closed?' => 'is_registration_closed?',
    'hiking_miles' => 'hiking_miles',
    'payment_required_to_rsvp' => 'payment_required_to_rsvp',
    'activity_at' => 'activity_at',
    'end_at' => 'end_at',
    'event_type' => 'event_type',
    'vcal' => 'vcal',
    'description' => 'description',
    'adult_fee' => 'adult_fee',
    'camping_nights' => 'camping_nights',
    'dues' => 'dues',
    'guests_allowed' => 'guests_allowed',
    'canoeing_miles' => 'canoeing_miles',
    'title' => 'title',
    'service_hours' => 'service_hours'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #Date by which RSVPs must be submitted
        'rsvp_deadline' => $args{'rsvp_deadline'}, 
        #ID of the event record
        'event_id' => $args{'event_id'}, 
        #Indicates if registration for this event is closed.
        'is_registration_closed?' => $args{'is_registration_closed?'}, 
        #Number of hiking miles that will occur at this event
        'hiking_miles' => $args{'hiking_miles'}, 
        #Indicates if payment is required to RSVP for this event. You cannot RSVP through the API if this is true.
        'payment_required_to_rsvp' => $args{'payment_required_to_rsvp'}, 
        #Start time of the event in 2014-11-20T02:00:00.000-06:00 format
        'activity_at' => $args{'activity_at'}, 
        #End time of the event in 2014-11-20T02:00:00.000-06:00 format
        'end_at' => $args{'end_at'}, 
        #Type of the event (Campout, Hike, Meeting, etc)
        'event_type' => $args{'event_type'}, 
        #VCAL representation of the event
        'vcal' => $args{'vcal'}, 
        #Description of the event
        'description' => $args{'description'}, 
        #Event fees required for each adult attending
        'adult_fee' => $args{'adult_fee'}, 
        #Number of nights of camping that will occur at this event
        'camping_nights' => $args{'camping_nights'}, 
        #Event fees required for each youth attending
        'dues' => $args{'dues'}, 
        #Indicates whether guests are allowed
        'guests_allowed' => $args{'guests_allowed'}, 
        #Number of canoeing miles that will occur at this event
        'canoeing_miles' => $args{'canoeing_miles'}, 
        #Title of the event
        'title' => $args{'title'}, 
        #Number of service hours per attendee that will occur at this event
        'service_hours' => $args{'service_hours'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
