package WWW::SwaggerClient::Object::EventTypeEntity;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'color' => 'string',
    'name' => 'string',
    'event_type_id' => 'int'
};

my $attribute_map = {
    'color' => 'color',
    'name' => 'name',
    'event_type_id' => 'event_type_id'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #Color used to display events of this type on the TroopTrack calendar
        'color' => $args{'color'}, 
        #Name of the event type (Campout, Meeting, etc)
        'name' => $args{'name'}, 
        #ID of the event type record
        'event_type_id' => $args{'event_type_id'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
