package WWW::SwaggerClient::Object::TroopPhotoEntity;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base "WWW::SwaggerClient::Object::BaseObject";

#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

my $swagger_types = {
    'troop_photo_id' => 'int',
    'photo' => 'int'
};

my $attribute_map = {
    'troop_photo_id' => 'troop_photo_id',
    'photo' => 'photo'
};

# new object
sub new { 
    my ($class, %args) = @_; 
    my $self = { 
        #ID of the Troop Photo record
        'troop_photo_id' => $args{'troop_photo_id'}, 
        #URL of the photo
        'photo' => $args{'photo'}
    }; 

    return bless $self, $class; 
}  

# get swagger type of the attribute
sub get_swagger_types {
    return $swagger_types;
}

# get attribute mappping
sub get_attribute_map {
    return $attribute_map;
}

1;
